name: Docker

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build vote Docker image
        run: |
          cd vote
          docker build -t $USERNAME/vote .

      - name: Build result Docker image
        run: |
          cd result
          docker build -t $USERNAME/result .

      - name: Build worker Docker image
        run: |
          cd worker
          docker build -t $USERNAME/worker .

      - name: Push vote Docker image
        run: docker push $USERNAME/vote

      - name: Push result Docker image
        run: docker push $USERNAME/result

      - name: Push worker Docker image
        run: docker push $USERNAME/worker

