name: Docker

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run:  docker-compose -f docker-compose.yml build

      - name: Push Docker image to Docker Hub
        run:  docker-compose -f docker-compose.yml push