name: Docker

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Push Docker Images
        run: |
          cd vote
          docker build -t $USERNAME/vote .
          docker push $USERNAME/vote
          cd ..

          cd result
          docker build -t $USERNAME/result .
          docker push $USERNAME/result
          cd ..

          cd worker
          docker build -t $USERNAME/worker .
          docker push $USERNAME/worker

